version: "3.8"

services:
  server:
    build:
      context: ./server
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./server/.env.dev
    ports:
      - 8000:8000
      - 3000:3000
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - database
      - elasticsearch


  database:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=products
      - POSTGRES_PASSWORD=products
      - POSTGRES_DB=products_dev
    ports:
      - 5432:5432

  elasticsearch:
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    image: elasticsearch:7.14.2
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  elasticsearch_data: